name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'snowflake'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

dbt-cloud:
  project-id: 70471823529856