-- =====================================================================
-- 01. RAW SCHEMA DDL
-- Source: S3 Ingestion & CSV Loads
-- =====================================================================

USE ROLE TRAINING_ROLE;
USE WAREHOUSE TED_AGENT_WH;
USE DATABASE TED_DB;
CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;

-- 1. TED_TALKS_DETAILS
CREATE TABLE IF NOT EXISTS TED_TALKS_DETAILS (
    ID INTEGER,
    SLUG STRING,
    INTERNAL_ID INTEGER,
    DESCRIPTION STRING,
    DURATION INTEGER,
    PRESENTER_DISPLAY_NAME STRING,
    PUBLISHED_AT TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. TED_TALKS_IMAGES
CREATE TABLE IF NOT EXISTS TED_TALKS_IMAGES (
    ID INTEGER,
    URL STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. TED_TALKS_LIST
CREATE TABLE IF NOT EXISTS TED_TALKS_LIST (
    ID INTEGER,
    SLUG STRING,
    SPEAKERS STRING,
    TITLE STRING,
    URL STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. TED_TALKS_RELATED_VIDEOS
CREATE TABLE IF NOT EXISTS TED_TALKS_RELATED_VIDEOS (
    ID INTEGER,
    RELATED_ID INTEGER,
    SLUG STRING,
    TITLE STRING,
    PRESENTER_DISPLAY_NAME STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. TED_TALKS_TAGS
CREATE TABLE IF NOT EXISTS TED_TALKS_TAGS (
    ID INTEGER,
    TAG STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. TED_TALKS_TRANSCRIPTS
CREATE TABLE IF NOT EXISTS TED_TALKS_TRANSCRIPTS (
    ID STRING,
    SLUG STRING,
    SPEAKERS STRING,
    TITLE STRING,
    URL STRING,
    TRANSCRIPT STRING
);
