-- =====================================================================
-- 04. APP SCHEMA DDL
-- Source: Streamlit Application State
-- =====================================================================

USE ROLE TRAINING_ROLE;
USE WAREHOUSE TED_AGENT_WH;
USE DATABASE TED_DB;
CREATE SCHEMA IF NOT EXISTS APP;
USE SCHEMA APP;

-- 1. USERS
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID VARCHAR(36) PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(64) NOT NULL,
    TOPICS_OF_INTEREST VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_LOGIN TIMESTAMP_NTZ
);

-- 2. USER_SEARCH_HISTORY
CREATE TABLE IF NOT EXISTS USER_SEARCH_HISTORY (
    SEARCH_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    SEARCH_QUERY VARCHAR(1000),
    RESULTS_COUNT INTEGER,
    SEARCHED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 3. USER_WATCH_HISTORY
CREATE TABLE IF NOT EXISTS USER_WATCH_HISTORY (
    WATCH_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    TALK_ID VARCHAR(50) NOT NULL,
    WATCH_DURATION_SECONDS INTEGER,
    TOTAL_DURATION_SECONDS INTEGER,
    WATCHED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 4. USER_PLAYLISTS
CREATE TABLE IF NOT EXISTS USER_PLAYLISTS (
    PLAYLIST_ID VARCHAR(36) DEFAULT UUID_STRING(),
    USER_ID VARCHAR(255) NOT NULL,
    TOPIC VARCHAR(500),
    CONTENT_MARKDOWN VARCHAR(16777216),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PLAYLIST_ID)
);

-- 5. USER_SAVED_NOTES
CREATE TABLE IF NOT EXISTS USER_SAVED_NOTES (
    NOTE_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    NOTE_TITLE VARCHAR(255) NOT NULL,
    CONVERSATION_DATA VARIANT,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 6. USER_CHAT_SESSIONS
CREATE TABLE IF NOT EXISTS USER_CHAT_SESSIONS (
    SESSION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    TITLE VARCHAR(255) DEFAULT 'New Chat',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 7. CHAT_MESSAGES
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    MESSAGE_ID VARCHAR(36) PRIMARY KEY,
    SESSION_ID VARCHAR(36) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    CONTENT VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (SESSION_ID) REFERENCES USER_CHAT_SESSIONS(SESSION_ID)
);
